security:
  password_hashers:
    App\Entity\User:
      algorithm: auto
  providers:
    users_in_memory: { memory: null }
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    main:
      lazy: true
      provider: users_in_memory
  access_control:
