services:
  App\Tests\Infrastructure\Security\FakeTokenValidator:
    autowire: true
    autoconfigure: true
    public: true
    
  App\Domain\Security\TokenValidatorInterface:
    alias: App\Tests\Infrastructure\Security\FakeTokenValidator
