parameters:
  auth_service_url: '%env(AUTH_SERVICE_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\EventListener\TokenValidationListener:
    arguments:
      $httpClient: '@http_client'
      $params: '@parameter_bag'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 10 }
    public: true

  App\EventListener\ApiExceptionListener:
    tags: 
      - { name: kernel.event_listener, event: kernel.exception }
