parameters:
  auth_service_base_url: '%env(AUTH_SERVICE_BASE_URL)'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\EventListener\TokenValidationListener:
    arguments:
      $httpClient: '@http_client'
      $loggerInterface: '@logger'
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 10 }
    public: true

  App\EventListener\ApiExceptionListener:
    tags: 
      - { name: kernel.event_listener, event: kernel.exception }
