parameters:
  auth_service_url: '%env(AUTH_SERVICE_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
      - '../src/Tests/'

  App\Domain\Repository\UserRepositoryInterface:
    alias: App\Infrastructure\Repository\UserRepository

  App\Domain\Service\UuidGeneratorInterface:
    alias: App\Infrastructure\Service\UuidGenerator

  App\Infrastructure\EventListener\TokenValidationListener:
    autowire: true
    tags:
      - { name: kernel.event_listener, event: kernel.request, priority: 10 }
    public: true

  App\Infrastructure\EventListener\ApiExceptionListener:
    tags: 
      - { name: kernel.event_listener, event: kernel.exception }

  App\Domain\Port\Security\TokenValidatorInterface:
    alias: App\Infrastructure\Security\TokenValidator

  Predis\Client:
    class: Predis\Client
    arguments:
      - '%env(CACHE_HOST)%'